version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached
      - media:/app/media
    environment:
      - DEBUG=1
    command: gunicorn pipeline_project.wsgi:application --bind 0.0.0.0:8000

volumes:
  media:
